SDK RUTX_R_GPL_00.07.22

diff --git a/package/network/services/pptpd/files/pptpd.init b/package/network/services/pptpd/files/pptpd.init
--- a/package/network/services/pptpd/files/pptpd.init
+++ b/package/network/services/pptpd/files/pptpd.init
@@ -9,7 +9,7 @@ TMP_DIR="/var/run/pptpd"
 CONFIG="${TMP_DIR}/pptpd.conf"
 CHAP_SECRETS="${TMP_DIR}/pptpd-chap-secrets"
 DEFAULT=/etc/default/pptpd
-OPTIONS="${TMP_DIR}/options.pptpd"
+STARTED=0
 
 service_triggers()
 {
@@ -33,30 +33,28 @@ setup_login() {
 
 append_options() {
 	local arg="$1"
-	[ -n "$arg" ] && echo "$arg" | sed -e 's/^[ \t]*//' >>"$OPTIONS"
+	[ -n "$arg" ] && echo "$arg" | sed -e 's/^[ \t]*//' >>"${TMP_DIR}/options.${2}"
 }
 
 setup_config() {
 	local enabled localip remoteip idle dns1 dns2
+	local section="$1"
 
-	config_get enabled "$1" enabled 0
-	[ "$enabled" -eq 0 ] && return 1
+	config_get idle "$section" idle
+	config_get dns1 "$section" dns1
+	config_get dns2 "$section" dns2
+	config_get mppe "$section" mppe
+	config_get mppe_encryption "$section" mppe_encryption
 
-	config_get idle "$1" idle
-	config_get dns1 "$1" dns1
-	config_get dns2 "$1" dns2
-	config_get mppe "$1" mppe
-	config_get mppe_encryption "$1" mppe_encryption
-
-	counter=$(( counter + 1 ))
-
-	mkdir -p /var/etc
 	cp /etc/pptpd.conf $CONFIG
-	echo -e "# MAIN PARAMETERS" > "$OPTIONS"
+	{
+		echo "option /var/run/pptpd/options.${section}"
+	} >> $CONFIG
+	echo -e "# MAIN PARAMETERS" > "${TMP_DIR}/options.${section}"
 
-	config_get localip "$1" localip
-	config_get remoteipstart "$1" start
-	config_get remoteipend "$1" limit
+	config_get localip "$section" localip
+	config_get remoteipstart "$section" start
+	config_get remoteipend "$section" limit
 
 	if [ -n "$remoteipstart" ] && [ -n "$remoteipend" ]; then
 		remoteip="${remoteipstart}-${remoteipend##*.}"
@@ -70,12 +68,12 @@ setup_config() {
 	} >> "$CONFIG"
 
 	{
-		echo "${idle:+idle  $idle}"
-		echo "${dns1:+ms-dns  $dns1}"
-		echo "${dns2:+ms-dns  $dns2}"
+		[ -n "$idle" ] && echo "idle $idle"
+		[ -n "$dns1" ] && echo "ms-dns $dns1"
+		[ -n "$dns2" ] && echo "ms-dns $dns2"
 		[ -z "$dns1" ] && [ -z "$dns2" ] && echo "ms-dns $localip"
 		[ "$mppe" = "none" ] && echo "nomppe"
-	} >> "$OPTIONS"
+	} >> "${TMP_DIR}/options.${section}"
 
 	if [ "$mppe" != "none" ]; then
 		encryptions="no40,no56,no128"
@@ -85,7 +83,7 @@ setup_config() {
 			done
 		fi
 		[ "$mppe" = "stateful" ] && mppe=""
-		echo "mppe required${encryptions:+,$encryptions}${mppe:+,$mppe}" >>"$OPTIONS"
+		echo "mppe required${encryptions:+,$encryptions}${mppe:+,$mppe}" >>"${TMP_DIR}/options.${section}"
 	fi
 
 	{
@@ -95,43 +93,59 @@ setup_config() {
 		echo "ifname pptp"
 		echo "name \"pptp-server\""
 		echo "chap-secrets ${TMP_DIR}/pptpd-chap-secrets"
-	} >> "$OPTIONS"
+		echo "encounter"
+	} >> "${TMP_DIR}/options.${section}"
 
-	echo -e "\n# CUSTOM PARAMETERS" >> $OPTIONS
-	config_list_foreach "$1" "pptp_options" append_options
+	echo -e "\n# CUSTOM PARAMETERS" >> "${TMP_DIR}/options.${section}"
+	config_list_foreach "$section" "pptp_options" append_options "$section"
 	return 0
+}
+
+start_instance() {
+	local section="$1"
+	config_get enabled "$section" enabled 0
+	if [ "$STARTED" -gt 0 ] || [ "$enabled" -eq 0 ]; then
+		return
+	fi
+
+	setup_config "$section"
+	[ -e "$CHAP_SECRETS" ] && rm -f $CHAP_SECRETS 2>/dev/null
+	config_foreach setup_login login
+
+	procd_open_instance
+	procd_set_param env LOGID=$section
+	procd_set_param command $BIN -p ${TMP_DIR}/pptpd.pid -c $CONFIG --fg
+	procd_set_param user pptpd
+	procd_close_instance
+	STARTED=1
 }
 
 start_service() {
 	# only run if "service" section exists in config
 	uci -q get pptpd.@service[0] &> /dev/null || return
 
-	local counter=0
-	[ -e "$CHAP_SECRETS" ] && rm -f $CHAP_SECRETS 2>/dev/null
-
-	config_load pptpd
-	config_foreach setup_config service
-	config_foreach setup_login login
-	chown -R pptpd:pptpd "${TMP_DIR}"
-
 	[ -f $DEFAULT ] && . $DEFAULT
 	for m in arc4 sha1_generic slhc crc-ccitt ppp_generic ppp_async ppp_mppe; do
-		insmod $m >/dev/null 2>&1
+		if [ ! -d "/sys/module/$m" ]; then
+			insmod $m >/dev/null 2>&1
+		fi
 	done
 
-	[ "$counter" -gt 0 ] && {
-		procd_open_instance
-		procd_set_param command $BIN -p ${TMP_DIR}/pptpd.pid -c $CONFIG --fg
-		procd_set_param user pptpd
-		procd_close_instance
-	}
+	config_load pptpd
+	config_foreach start_instance service
+
+	[ "$STARTED" -eq 1 ] || return
+	[ -d /var/state/pptp ] || mkdir -p /var/state/pptp
+	date "+%s" > /var/state/pptp/uptime
+	chown -R pptpd:pptpd /var/state/pptp
 }
 
 stop_service() {
-	instances=$(ps | grep -v grep | grep "options.pptpd" | awk '{print $1}' ORS=' ')
+	instances=$(ps | grep -v grep | grep "pppd local file /var/run/pptpd/options." | awk '{print $1}' ORS=' ')
 	for inst in $instances; do
 		kill $inst
 	done
+	[ -f /var/state/pptp/uptime ] && rm -f /var/state/pptp/uptime
 }
 
 reload_service() {
diff --git a/package/system/opkg/files/opkg-cleanup b/package/system/opkg/files/opkg-cleanup
--- a/package/system/opkg/files/opkg-cleanup
+++ b/package/system/opkg/files/opkg-cleanup
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+OVERLAY_DIR="/usr/local"
+DEFAULT_IPK_DIR="/tmp/run/opkg/custom_package"
+
 log() {
     logger "opkg-cleanup.sh: $1"
 }
@@ -32,13 +35,29 @@ done
 
 [ -z "$TEMPDIR" ] || [ -z "$PKG_NAME" ] && usage
 
-PACKAGE_FILE_NAME=$(find "$TEMPDIR" -name "$PKG_NAME*.ipk")
+[ ! -d "$TEMPDIR" ] && {
+    log "IPK directory '$TEMPDIR' does not exist"
+    [ -d "$DEFAULT_IPK_DIR" ] || {
+        exit 1
+    }
+
+    log "Using default IPK directory '$DEFAULT_IPK_DIR'"
+    TEMPDIR="$DEFAULT_IPK_DIR"
+}
+
+PACKAGE_FILE_NAME=$(find "$TEMPDIR" -name "${PKG_NAME}_*.ipk")
+[ -z "$PACKAGE_FILE_NAME" ] && {
+    log "Package file for package '$PKG_NAME' not found in directory '$TEMPDIR'"
+    exit 1
+}
+
 PACKAGE_FILES=$(< "$PACKAGE_FILE_NAME" tar -Oxz ./data.tar.gz | tar -tz | grep -vE '^\./$' | sort -r | sed 's/^\.//')
-OPKG_STATUS_FILE="/usr/lib/opkg/status"
+OPKG_STATUS_FILE="${OVERLAY_DIR}/lib/opkg/status"
 OPKG_STATUS_TMP_FILE="/tmp/tmp_status.txt"
 
 for PACKAGE_FILE in $PACKAGE_FILES
 do
+    PACKAGE_FILE="${OVERLAY_DIR}${PACKAGE_FILE}"
     if [ -f "$PACKAGE_FILE" ] || [ -L "$PACKAGE_FILE" ]
     then
         log "removing file: '$PACKAGE_FILE'"
@@ -51,7 +70,7 @@ do
     fi
 done
 
-CONTROL_FILES=$(ls /usr/lib/opkg/info/"$PKG_NAME"* 2> /dev/null || true)
+CONTROL_FILES=$(ls "${OVERLAY_DIR}/lib/opkg/info/$PKG_NAME"* 2> /dev/null || true)
 for CONTROL_FILE in $CONTROL_FILES
 do
     log "removing control file: '$CONTROL_FILE'"
