SDK RUTX_R_GPL_00.07.06

diff --git a/package/teltonika/ledman/bin/files/ledman.init b/package/teltonika/ledman/bin/files/ledman.init
--- a/package/teltonika/ledman/bin/files/ledman.init
+++ b/package/teltonika/ledman/bin/files/ledman.init
@@ -8,26 +8,171 @@ NAME=ledman
 ARGS="-d"
 PROG=/usr/bin/$NAME
 
+load_led() {
+	local name
+	local sysfs
+	local trigger
+	local dev
+	local ports
+	local mode
+	local default
+	local delayon
+	local delayoff
+	local interval
+
+	config_get sysfs $1 sysfs
+	config_get name $1 name "$sysfs"
+	config_get trigger $1 trigger "none"
+	config_get dev $1 dev
+	config_get ports $1 port
+	config_get mode $1 mode
+	config_get_bool default $1 default "0"
+	config_get delayon $1 delayon
+	config_get delayoff $1 delayoff
+	config_get interval $1 interval "50"
+	config_get port_state $1 port_state
+	config_get delay $1 delay "150"
+	config_get message $1 message ""
+	config_get gpio $1 gpio "0"
+	config_get inverted $1 inverted "0"
+
+	if [ $2 -ne 1 ]; then
+		trigger="none"
+	fi
+
+
+	if [ "$trigger" = "rssi" ]; then
+		# handled by rssileds userspace process
+		return
+	fi
+
+	[ "$trigger" = "usbdev" ] && {
+		# Backward compatibility: translate to the new trigger
+		trigger="usbport"
+		# Translate port of root hub, e.g. 4-1 -> usb4-port1
+		ports=$(echo "$dev" | sed -n 's/^\([0-9]*\)-\([0-9]*\)$/usb\1-port\2/p')
+		# Translate port of extra hub, e.g. 2-2.4 -> 2-2-port4
+		[ -z "$ports" ] && ports=$(echo "$dev" | sed -n 's/\./-port/p')
+	}
+
+	[ -e /sys/class/leds/${sysfs}/brightness ] && {
+		echo "setting up led ${name}"
+
+		printf "%s %s %d\n" \
+			"$sysfs" \
+			"$(sed -ne 's/^.*\[\(.*\)\].*$/\1/p' /sys/class/leds/${sysfs}/trigger)" \
+			"$(cat /sys/class/leds/${sysfs}/brightness)" \
+				>> /var/run/led.state
+
+		[ "$default" = 0 ] &&
+			echo 0 >/sys/class/leds/${sysfs}/brightness
+
+		echo $trigger > /sys/class/leds/${sysfs}/trigger 2> /dev/null
+		ret="$?"
+
+		[ $default = 1 ] &&
+			cat /sys/class/leds/${sysfs}/max_brightness > /sys/class/leds/${sysfs}/brightness
+
+		[ $ret = 0 ] || {
+			echo >&2 "Skipping trigger '$trigger' for led '$name' due to missing kernel module"
+			return 1
+		}
+		case "$trigger" in
+		"netdev")
+			[ -n "$dev" ] && {
+				echo $dev > /sys/class/leds/${sysfs}/device_name
+				for m in $mode; do
+					[ -e "/sys/class/leds/${sysfs}/$m" ] && \
+						echo 1 > /sys/class/leds/${sysfs}/$m
+				done
+				echo $interval > /sys/class/leds/${sysfs}/interval
+			}
+			;;
+
+		"timer"|"oneshot")
+			[ -n "$delayon" ] && \
+				echo $delayon > /sys/class/leds/${sysfs}/delay_on
+			[ -n "$delayoff" ] && \
+				echo $delayoff > /sys/class/leds/${sysfs}/delay_off
+			;;
+
+		"usbport")
+			local p
+
+			for p in $ports; do
+				echo 1 > /sys/class/leds/${sysfs}/ports/$p
+			done
+			;;
+
+		"port_state")
+			[ -n "$port_state" ] && \
+				echo $port_state > /sys/class/leds/${sysfs}/port_state
+			;;
+
+		"gpio")
+			echo $gpio > /sys/class/leds/${sysfs}/gpio
+			echo $inverted > /sys/class/leds/${sysfs}/inverted
+			;;
+
+		switch[0-9]*)
+			local port_mask speed_mask
+
+			config_get port_mask $1 port_mask
+			[ -n "$port_mask" ] && \
+				echo $port_mask > /sys/class/leds/${sysfs}/port_mask
+			config_get speed_mask $1 speed_mask
+			[ -n "$speed_mask" ] && \
+				echo $speed_mask > /sys/class/leds/${sysfs}/speed_mask
+			[ -n "$mode" ] && \
+				echo "$mode" > /sys/class/leds/${sysfs}/mode
+			;;
+		esac
+	}
+}
+
 start_service() {
+	config_load system
+	config_get led_enabl "ledman" enabled 1
+	procd_open_instance
+	[ -e /sys/class/leds/ ] && {
+		[ -s /var/run/led.state ] && {
+			procd_set_param file /etc/config/system
+			local led trigger brightness
+			while read led trigger brightness; do
+				if [ $led_enabl -eq 1 ]; then
+					[ -e "/sys/class/leds/$led/trigger" ] && \
+						echo "$trigger" > "/sys/class/leds/$led/trigger"
+
+					[ -e "/sys/class/leds/$led/brightness" ] && \
+						echo "$brightness" > "/sys/class/leds/$led/brightness"
+				else
+					[ -e "/sys/class/leds/$led/trigger" ] && \
+						echo "none" > "/sys/class/leds/$led/trigger"
+
+					[ -e "/sys/class/leds/$led/brightness" ] && \
+						echo "0" > "/sys/class/leds/$led/brightness"
+				fi
+			done < /var/run/led.state
+			rm /var/run/led.state
+		}
+		config_foreach load_led led $led_enabl
+	}
+
 	# the following file is created on failed stm32 upgrade
 	# since stm32 is registered in device tree, kernel will spam
 	#  `gpio-chip gone` messages if ledman will be running
 	# so we need to prevent ledman from running if upgrade was failed
-	if [ -f /tmp/stm32_fail ]; then
-		return
+	if [ ! -f /tmp/stm32_fail ]; then
+		procd_set_param command "$PROG" "$ARGS"
+		procd_set_param stdout 1
+		procd_set_param stderr 1
+
+		# If ledman is disabled, then we do not need to setup 'respawn'. In this case when ledman
+		# exits with error code 0 or anu other, no ledman crash message will be generated in logread.
+		[ "$(uci get system.ledman.enabled 2>/dev/null)" != 0 ] && {
+			procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
+		}
 	fi
-
-	procd_open_instance
-
-	procd_set_param command "$PROG" "$ARGS"
-	procd_set_param stdout 1
-	procd_set_param stderr 1
-
-	# If ledman is disabled, then we do not need to setup 'respawn'. In this case when ledman 
-	# exits with error code 0 or anu other, no ledman crash message will be generated in logread.
-	[ "$(uci get system.ledman.enabled 2>/dev/null)" != 0 ] && {
-		procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
-	}
 
 	procd_close_instance
 }
diff --git a/package/teltonika/quectel/quectel_dfota/files/dfota b/package/teltonika/quectel/quectel_dfota/files/dfota
--- a/package/teltonika/quectel/quectel_dfota/files/dfota
+++ b/package/teltonika/quectel/quectel_dfota/files/dfota
@@ -24,13 +24,17 @@ EC_EDL_FAILED="172"
 EC_DL_FAILED="173"
 EC_UPD_VERIFY_FAILED="174"
 EC_UPD_START_FAILED="175"
+EC_UPGRADE_START_ERROR="176"
 
 #prepare ENV
 modem_ids=""
 forced="false"
 update="false"
+MODE=""
+UPDATE_MODEM=""
 firmware_size=0
 export_info=0
+less_status=0
 export_status=0
 a_modem_id="" # Modem ID from arguments
 status="$UPDATE_SUCCESS"
@@ -39,6 +43,8 @@ json_file_status="/tmp/dfota_status.json"
 LAST_ERROR=""
 LAST_ERROR_CODE=""
 UPDATE_FAILED="0"
+
+TOTAL_LIST_RETRIES=10
 
 get_from_info() {
 	ubus call "$1" info | grep "$2" | cut -d'"' -f 4
@@ -67,6 +73,9 @@ print_help() {
 	Options:
 	-h	Print help message
 	-u	Check if there is an update available and start the update
+	-l	<url>	Update modem by link
+	-f	<path>	Update modem by file
+	-m	<id>	Modem id to update. (gsm.modem0, gsm.modem1...)
 	-e	Export JSON to $json_file_updates about available updates
 	-s	Export JSON to $json_file_status about update status
 	-w	Wait for default route and modem to appear
@@ -79,7 +88,22 @@ while [ -n "$1" ]; do
 		-w) export WAIT_FOR_WAN=1;;
 		-d) debug=1;;
 		-u) update="true";;
+		-l)
+			shift
+			MODE="link"
+			MODE_PATH="$1"
+		;;
+		-f)
+			shift
+			MODE="file"
+			MODE_PATH="$1"
+		;;
+		-m)
+			shift
+			UPDATE_MODEM="$1"
+		;;
 		-e) export_info=1;;
+		-k) less_status=1;;
 		-s)
 			export_status=1
 			[ -f "$json_file_status" ] && rm "$json_file_status"
@@ -172,6 +196,11 @@ notify_webui() {
 		stop)
 			mkdir -p /tmp/vuci
 			touch /tmp/vuci/dfota_finish
+			rm -rf /tmp/dfota_update
+			;;
+		error)
+			mkdir -p /tmp/vuci
+			touch /tmp/vuci/dfota_error
 			rm -rf /tmp/dfota_update
 			;;
 	esac
@@ -297,6 +326,8 @@ check_modem_status() {
 }
 
 check_update() {
+	[ -n "$MODE" ] && print_output "Skipping update checking because direct file or link provided" && return
+
 	#Check if there is available update
 	local modem_id="$1"
 	forced="false"
@@ -336,6 +367,14 @@ do_update() {
 	local modem_id="$1"
 	local ret
 
+	# Sets size for modem to expect
+	[ "$MODE" == "link" ] && firmware_size=$(curl -sI "$MODE_PATH" | awk -e '$0 ~ /^Content-Length: ([0-9]+)/ { print $2 }')
+	[ "$MODE" == "file" ] && firmware_size=$(du -b "$MODE_PATH" | awk '{print $1}')
+	[ -n "$MODE" ] && [ -z "$firmware_size" ] && {
+		print_error "Failed to get firmware_size from $MODE_PATH"
+		return 1
+	}
+
 	print_output "Preparing system for update!"
 
 	ubus call "$modem_id" delete_file "{\"path\":\"UFS:dfota.zip\"}" > /dev/null 2>&1
@@ -366,18 +405,32 @@ do_update() {
 
 	print_output "Starting download!"
 	json_update_modem_status "$modem_id" "downloading"
+	notify_webui "start"
 	# Add notification to rut_fota about start of downloading
-	rut_fota --notify_server
-	curl -s --ssl --connect-timeout 30 --max-time 900 -L "$download_link" -o "$cmd_port"
-	ret="$?"
+	[ -z "$MODE" ] && rut_fota --notify_server
+	if [ "$MODE" = "file" ]; then
+		cat "$MODE_PATH" > "$cmd_port"
+	else
+		if [ "$MODE" = "link" ]; then
+			download_link="$MODE_PATH"
+		fi
+		curl -s --ssl-reqd --connect-timeout 30 --max-time 900 -L "$download_link" -o "$cmd_port"
+	fi
 
-	sleep 2
+	ret="$?"
 
 	[ "$ret" = "0" ] || {
 		print_error "Firmware update download was unsuccessful. Error: $ret" "$EC_DL_FAILED"
 		return 1
 	}
-	get_file_list_result=$(ubus call "$modem_id" get_file_list "{\"path\":\"UFS:dfota.zip\"}" )
+
+	for i in $(seq $TOTAL_LIST_RETRIES); do
+		sleep 2
+		get_file_list_result=$(ubus call "$modem_id" get_file_list "{\"path\":\"UFS:dfota.zip\"}")
+		[ -z $(echo "$get_file_list_result" | grep "error") ] && break
+		debug "($i/$TOTAL_LIST_RETRIES) Retrying to get file list"
+	done
+
 	dl_file_size=$( echo "$get_file_list_result" | grep "size" | cut -d'"' -f 3 | cut -c 3- )
 	[ -n "$dl_file_size" ] &&\
 	[ -n "$firmware_size" ] &&\
@@ -397,7 +450,7 @@ do_update() {
 		ret=$(ubus call "$modem_id" dfota_upgrade "{\"path\":\"/cache/ufs/dfota.zip\"}")
 		ret=$(get_value_from_json "$ret" "status")
 		[ "$ret" == "OK" ] && return 0
-	
+
 		print_error "Unable to start firmware update process!" "$EC_UPD_START_FAILED"
 		return 1
 
@@ -416,7 +469,20 @@ track_update_status() {
 	print_output "Waiting for the update to start..."
 	json_update_modem_status "$modem_id" "waiting"
 	modem_usb_id=$(get_from_info "$modem_id" "usb_id")
+
+	# Counter and max wait time
+	counter=0
+	max_wait=30
+
 	while [ -e "/sys/bus/usb/devices/$modem_usb_id" ]; do
+		counter=$((counter+1))
+		if [ $counter -ge $max_wait ]; then
+			print_error "Unable to start update process" $EC_UPGRADE_START_ERROR
+			json_update_modem_error "$modem_id" "$LAST_ERROR" "$LAST_ERROR_CODE"
+			json_update_dfota_status "finished" "$UPDATE_FAILED"
+			end "$UPDATE_ERROR" "Update script done!"
+		fi
+
 		sleep 1
 	done
 
@@ -524,6 +590,10 @@ _json_update_dfota_status(){
 json_update_dfota_status(){
 	[ "$export_status" -eq 1 ] && {
 		_json_update_dfota_status "$1" "$2"
+		[ "$2" -ne 1 ] && return
+
+		[ "$less_status" -eq 0 ] || { [ "$LAST_ERROR_CODE" != "$EC_NO_UPDATE" ] &&
+		[ "$LAST_ERROR_CODE" != "$EC_NOT_QUECTEL" ]; } && notify_webui "error"
 	}
 }
 
@@ -555,8 +625,11 @@ json_update_modem_error(){
 
 update_loop(){
 	#Iterate modem ids
+	local modem_found=""
 	for m_id in $modem_ids; do
+		[ -n "$UPDATE_MODEM" ] && [ "$m_id" != "$UPDATE_MODEM" ] && continue
 		print_output "Preparing for $m_id update!"
+		modem_found="true"
 
 		check_modem_status "$m_id" || {
 			json_update_modem_error "$m_id" "$LAST_ERROR" "$LAST_ERROR_CODE"
@@ -586,6 +659,11 @@ update_loop(){
 		fi
 	done
 
+	[ -n "$UPDATE_MODEM" ] && [ -z "$modem_found" ] && {
+		print_error "Failed to select $UPDATE_MODEM modem." "$MODEM_NOT_FOUND"
+		exit 1
+	}
+
 	reset_on_fail "$status"
 	json_update_dfota_status "finished" "$UPDATE_FAILED"
 	end "$status" "Update script done!"
@@ -600,6 +678,8 @@ if [ "$(pgrep -f "$0")" != "$$" ]; then
 fi
 
 [ "$export_info" -eq 1 ] && [ "$update" = "true" ] && end "$BAD_ARGUMENTS" "Please define only -e or -u in arguments!"
+
+[ "$export_status" -eq 1 ] && [ "$less_status" -eq 0 ] &&  json_update_dfota_status "started" 0
 
 #Wait for full system boot
 while true; do
