SDK RUTX_R_GPL_00.07.11

diff --git a/package/base-files/files/etc/init.d/done b/package/base-files/files/etc/init.d/done
--- a/package/base-files/files/etc/init.d/done
+++ b/package/base-files/files/etc/init.d/done
@@ -4,69 +4,84 @@
 START=16
 
 _check_paths() {
-	for id in $@; do
-		path="/sys/bus/usb/drivers/usb/$id"
-		[ ! -d $path ] && return 1
+	for sub_path in $1; do
+		[ ! -d $sub_path ] && return 1
 	done
 
 	return 0
 }
 
-usbcheck_passed() {
-	echo "USB system start up: OK"
-	uci -q set system.usbcheck.counter='0'
+check_passed() {
+	echo "$1 passed"
+	uci -q set system.$1.counter='0'
 	uci commit system
 
 	return 0
+}
+
+handle_usbhub_reset() {
+		gpio_path="/sys/class/gpio/$3/value"
+		[ ! -f "$gpio_path" ] && echo "Error: Couldn't find $3 gpio" && return
+
+		for count in $(seq 3); do
+			echo "USB hub not detected, resetting" > /dev/kmsg
+			echo 1 > $gpio_path
+			sleep 1
+			echo 0 > $gpio_path
+			sleep 2
+			_check_paths "$2" && echo "$1 passed" && return
+		done
+
+		echo "$1 failed"
+}
+
+handle_reboot() {
+	disable="$(uci -q get system.modem.disable)"
+	name=$1
+
+	if [ $name = "usbcheck" ] && [ -n "$disable" ] && [ "$disable" -eq 1 ]; then
+		check_passed "$name"
+	else
+		for _ in $(seq 0 5); do
+			[ -d "$2" ] && check_passed "$name" && return 0
+			sleep 5
+		done
+
+		cnt=$(uci -q get system.$name.counter)
+		max=$(uci -q get system.$name.max)
+		if [ "$max" -gt "$cnt" ]; then
+			cnt=$((cnt+1))
+			uci -q set system.$name.counter=$cnt
+			uci commit system
+			echo "$name failed - rebooting system, count $cnt"
+			sync && reboot -f
+		else
+			echo "$name failed after $cnt count"
+		fi
+	fi
 }
 
 boot() {
 	mount_root done
 	rm -f /sysupgrade.tgz && sync
 
-	#Reset USB hub if it is not detected
-	usb_id="$(jsonfilter -i /etc/board.json -e '@.usbhubcheck.usb_id')"
-
-	if [ -n "$usb_id" ]; then
-		gpio="$(jsonfilter -i /etc/board.json -e '@.usbhubcheck.gpio')"
-		gpio_path="/sys/class/gpio/${gpio}/value"
-
-		if ! _check_paths "$usb_id" && [ -f "$gpio_path" ]; then
-			for count in $(seq 3); do 
-				echo "USB hub not detected, resetting" > /dev/kmsg
-				echo 1 > $gpio_path
-				sleep 1
-				echo 0 > $gpio_path
-				sleep 2
-				_check_paths "$usb_id" && break
-			done
-		fi
-	fi
-
-	# Reboot if usb subsystem doesn't start properly
-	if [ -n "$(uci -q get system.usbcheck.path)" ]; then
-		disable="$(uci -q get system.modem.disable)"
-		path="$(uci -q get system.usbcheck.path)"
-
-		if [ -z "$disable" ] || [ "$disable" -eq 0 2>/dev/null ]; then
-			for i in $(seq 0 5); do
-				[ -d "$path" ] && usbcheck_passed && return 0
-				sleep 5
-			done
-
-			echo "USB system start up FAILED"
-			cnt=$(uci -q get system.usbcheck.counter)
-			max=$(uci -q get system.usbcheck.max)
-
-			if [ "$max" -gt "$cnt" ]; then
-				cnt=$((cnt+1))
-				uci -q set system.usbcheck.counter=$cnt
-				uci commit system
-				echo "Rebooting..."
-				sync && reboot -f
+	index=1
+	while : ; do
+		found=1
+		name=$(jsonfilter -i /etc/board.json -e "@.checks[$((index - 1))].name")
+		path=$(jsonfilter -i /etc/board.json -e "@.checks[$((index - 1))].path")
+		action=$(jsonfilter -i /etc/board.json -e "@.checks[$((index - 1))].action")
+		[[ -z "$name" || -z "$path" || -z "$action" ]] && break
+		if ! _check_paths "$path" ; then
+			if [ "$name" = "usbhub_check" ]; then
+				handle_usbhub_reset "$name" "$path" "$action"
+			elif [ "$action" = "reboot" ]; then
+				handle_reboot "$name" "$path"
 			fi
 		else
-			usbcheck_passed
+			[ "$action" = "reboot" ] && check_passed "$name"
 		fi
-	fi
+
+		index=$((index + 1))
+	done
 }
diff --git a/package/system/ubox/files/log.init b/package/system/ubox/files/log.init
--- a/package/system/ubox/files/log.init
+++ b/package/system/ubox/files/log.init
@@ -12,6 +12,7 @@ PROG=/sbin/logread
 validate_log_section() {
 	uci_load_validate system system "$1" "$2" \
 		'log_file:string' \
+		'log_compress:bool:1' \
 		'log_size:uinteger' \
 		'log_ip:string' \
 		'log_remote:bool:1' \
@@ -38,29 +39,6 @@ start_service_daemon() {
 	procd_close_instance
 }
 
-start_service_file() {
-	PIDCOUNT="$((PIDCOUNT + 1))"
-	local pid_file="/var/run/logread.${PIDCOUNT}.pid"
-	local log_dir
-
-	[ "$2" = 0 ] || {
-		echo "validation failed"
-		return 1
-	}
-	[ -z "${log_file}" ] && return
-
-	#Create log directory if does not exist
-	log_dir=$(dirname "${log_file}")
-	[ -d "${log_dir}" ] || mkdir -p "${log_dir}"
-
-	procd_open_instance
-	procd_set_param command "$PROG" -f -F "$log_file" -p "$pid_file"
-	[ -n "${log_size}" ] && \
-		[ -z "${log_file}" ] \
-		&& procd_append_param command -S "$log_size"
-	procd_close_instance
-}
-
 start_service_remote() {
 	PIDCOUNT="$((PIDCOUNT + 1))"
 	local pid_file="/var/run/logread.${PIDCOUNT}.pid"
@@ -83,14 +61,35 @@ start_service_remote() {
 	procd_close_instance
 }
 
-start_service_db() {
+start_service_local() {
 	PIDCOUNT="$((PIDCOUNT + 1))"
 	local pid_file="/var/run/logread.${PIDCOUNT}.pid"
+	local log_dir
+
+	[ "$2" = 0 ] || {
+		echo "Validation failed for local logging"
+		return 1
+	}
+	[ -n "${log_file}" ] && {
+		# Create log directory if it does not exist
+		log_dir=$(dirname "${log_file}")
+		[ -d "${log_dir}" ] || mkdir -p "${log_dir}"
+	}
 
 	procd_open_instance
 	procd_set_param command "$PROG" -f -i -p "$pid_file"
+
+	[ -n "${log_size}" ] && procd_append_param command -S "$log_size"
+	[ -n "${log_file}" ] && procd_append_param command -F "$log_file"
+	[[ "${log_compress}" -eq "1" && -n "${log_file}" ]] && procd_append_param command -c "$log_compress"
 	procd_set_param respawn 3600 5 0
 	procd_close_instance
+
+	if [ -n "$pid_file" ]; then
+		echo "PID file created: $pid_file"
+	else
+		echo "Failed to create PID file: $pid_file"
+	fi
 }
 
 service_triggers() {
@@ -101,7 +100,6 @@ service_triggers() {
 start_service() {
 	config_load system
 	config_foreach validate_log_daemon system start_service_daemon
-	config_foreach validate_log_section system start_service_file
+	config_foreach validate_log_section system start_service_local
 	config_foreach validate_log_section remote_logger start_service_remote
-	config_foreach start_service_db system
 }
