SDK RUTX_R_GPL_00.07.06.5

diff --git a/scripts/ipkg-build b/scripts/ipkg-build
--- a/scripts/ipkg-build
+++ b/scripts/ipkg-build
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # ipkg-build -- construct a .ipk from a directory
 # Carl Worth <cworth@east.isi.edu>
@@ -9,7 +9,7 @@
 #   For UID debugging it needs a better "find".
 set -e
 
-version=1.0
+version=2.0
 FIND="$(command -v find)"
 FIND="${FIND:-$(command -v gfind)}"
 TAR="${TAR:-$(command -v tar)}"
@@ -31,30 +31,32 @@ ipkg_extract_value() {
 required_field() {
 	field=$1
 
-	grep "^$field:" < $CONTROL/control | ipkg_extract_value
+	grep "^$field:" <$CONTROL/control | ipkg_extract_value
 }
 
 pkg_appears_sane() {
 	local pkg_dir=$1
 
 	local owd=$PWD
-	cd $pkg_dir
+	cd "$pkg_dir"
 
 	PKG_ERROR=0
-	pkg=`required_field Package`
-	version=`required_field Version | sed 's/Version://; s/^.://g;'`
-	arch=`required_field Architecture`
+	pkg=$(required_field Package)
+	version=$(required_field Version | sed 's/Version://; s/^.://g;')
+	arch=$(required_field Architecture)
 
-	if echo $pkg | grep '[^a-zA-Z0-9_.+-]'; then
+	if echo "$pkg" | grep '[^a-zA-Z0-9_.+-]'; then
 		echo "*** Error: Package name $name contains illegal characters, (other than [a-z0-9.+-])" >&2
-		PKG_ERROR=1;
+		PKG_ERROR=1
 	fi
 
 	if [ -f $CONTROL/conffiles ]; then
 		rm -f $CONTROL/conffiles.resolved
 
-		for cf in `$FIND $(sed -e "s!^/!$pkg_dir/!" $CONTROL/conffiles) -type f`; do
-			echo "${cf#$pkg_dir}" >> $CONTROL/conffiles.resolved
+		# shellcheck disable=2046
+		for cf in $($FIND $(sed -e "s!^/!$pkg_dir/!" $CONTROL/conffiles) -type f); do
+			# shellcheck disable=2295
+			echo "${cf#$pkg_dir}" >>$CONTROL/conffiles.resolved
 		done
 
 		rm $CONTROL/conffiles
@@ -64,7 +66,7 @@ pkg_appears_sane() {
 		fi
 	fi
 
-	cd $owd
+	cd "$owd"
 	return $PKG_ERROR
 }
 
@@ -72,14 +74,14 @@ resolve_file_mode_id() {
 	local var=$1 type=$2 name=$3 id
 
 	case "$name" in
-		root)
-			id=0
+	root)
+		id=0
 		;;
-		*[!0-9]*)
-			id=$(sed -ne "s#^$type $name \\([0-9]\\+\\)\\b.*\$#\\1#p" "$TOPDIR/tmp/.packageusergroup" 2>/dev/null)
+	*[!0-9]*)
+		id=$(sed -ne "s#^$type $name \\([0-9]\\+\\)\\b.*\$#\\1#p" "$TOPDIR/tmp/.packageusergroup" 2>/dev/null)
 		;;
-		*)
-			id=$name
+	*)
+		id=$name
 		;;
 	esac
 
@@ -92,20 +94,26 @@ resolve_file_mode_id() {
 # ipkg-build "main"
 ###
 file_modes=""
-usage="Usage: $0 [-v] [-h] [-m] <pkg_directory> [<destination_directory>]"
-while getopts "hvm:" opt; do
-    case $opt in
-	v ) echo $version
-	    exit 0
-	    ;;
-	h ) 	echo $usage  >&2 ;;
-	m )	file_modes=$OPTARG ;;
-	\? ) 	echo $usage  >&2
+prepare=false
+pack=false
+usage="Usage: $0 [-v] [-u|-p] [-h] [-m] <pkg_directory> [<destination_directory>]"
+while getopts "hvm:u:p" opt; do
+	case $opt in
+	v)
+		echo $version
+		exit 0
+		;;
+	m) file_modes=$OPTARG ;;
+	u)
+		prepare=true
+		sign_file_list=$OPTARG
+		;;
+	p) pack=true ;;
+	h | \?) echo "$usage" >&2 ;;
 	esac
 done
 
-
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
 # continue on to process additional arguments
 
@@ -115,93 +123,116 @@ case $# in
 	;;
 2)
 	dest_dir=$2
-	if [ "$dest_dir" = "." -o "$dest_dir" = "./" ] ; then
-	    dest_dir=$PWD
+	if [[ $dest_dir = "." || $dest_dir = "./" ]]; then
+		dest_dir=$PWD
 	fi
 	;;
 *)
-	echo $usage >&2
+	echo "$usage" >&2
 	exit 1
 	;;
 esac
 
 pkg_dir=$1
 
-if [ ! -d $pkg_dir ]; then
+if [ ! -d "$pkg_dir" ]; then
 	echo "*** Error: Directory $pkg_dir does not exist" >&2
 	exit 1
 fi
 
 # CONTROL is second so that it takes precedence
 CONTROL=
-[ -d $pkg_dir/CONTROL ] && CONTROL=CONTROL
+[ -d "$pkg_dir/CONTROL" ] && CONTROL=CONTROL
 if [ -z "$CONTROL" ]; then
 	echo "*** Error: Directory $pkg_dir has no CONTROL subdirectory." >&2
 	exit 1
 fi
 
-if ! pkg_appears_sane $pkg_dir; then
+if ! pkg_appears_sane "$pkg_dir"; then
 	echo >&2
 	echo "ipkg-build: Please fix the above errors and try again." >&2
 	exit 1
 fi
 
-tmp_dir=$dest_dir/IPKG_BUILD.$$
-mkdir $tmp_dir
-# shellcheck disable=2064
-trap "rm -rf $tmp_dir" EXIT INT TERM
+tmp_dir=$dest_dir/$pkg
+tmp_concat="$tmp_dir/control+data.tmp"
+# shellcheck disable=2046,2064
+trap "rm -rf $tmp_dir" INT TERM $($prepare || echo EXIT)
 
-echo $CONTROL > $tmp_dir/tarX
-cd $pkg_dir
-for file_mode in $file_modes; do
-	case $file_mode in
-	/*:*:*:*)
-	    ;;
-	*)
-	    echo "ERROR: file modes must use absolute path and contain user:group:mode"
-	    echo "$file_mode"
-	    exit 1
-	    ;;
-	esac
+prepare() {
+	local sign_file_list=$1
 
-	mode=${file_mode##*:}; path=${file_mode%:*}
-	group=${path##*:};     path=${path%:*}
-	user=${path##*:};      path=${path%:*}
+	mkdir "$tmp_dir"
 
-	if ! resolve_file_mode_id uid user "$user"; then
-		echo "ERROR: unable to resolve uid of $user" >&2
-		exit 1
-	fi
+	echo $CONTROL >"$tmp_dir/tarX"
+	cd "$pkg_dir"
+	for file_mode in $file_modes; do
+		case $file_mode in
+		/*:*:*:*) ;;
+		*)
+			echo "ERROR: file modes must use absolute path and contain user:group:mode"
+			echo "$file_mode"
+			exit 1
+			;;
+		esac
 
-	if ! resolve_file_mode_id gid group "$group"; then
-		echo "ERROR: unable to resolve gid of $group" >&2
-		exit 1
-	fi
+		mode=${file_mode##*:}
+		path=${file_mode%:*}
+		group=${path##*:}
+		path=${path%:*}
+		user=${path##*:}
+		path=${path%:*}
 
-	chown "$uid:$gid" "$pkg_dir/$path"
-	chmod  "$mode" "$pkg_dir/$path"
-done
+		if ! resolve_file_mode_id uid user "$user"; then
+			echo "ERROR: unable to resolve uid of $user" >&2
+			exit 1
+		fi
 
-$TAR -X $tmp_dir/tarX --format=gnu --sort=name -cpf - --mtime="$TIMESTAMP" . | $GZIP -n - > $tmp_dir/data.tar.gz
-installed_size=$(stat -c "%s" $tmp_dir/data.tar.gz)
+		if ! resolve_file_mode_id gid group "$group"; then
+			echo "ERROR: unable to resolve gid of $group" >&2
+			exit 1
+		fi
 
-sed -i -e "s/^Installed-Size: .*/Installed-Size: $installed_size/" \
-	$pkg_dir/$CONTROL/control
+		# shellcheck disable=2154
+		chown "$uid:$gid" "$pkg_dir/$path"
+		chmod "$mode" "$pkg_dir/$path"
+	done
 
-( cd $pkg_dir/$CONTROL && $TAR --format=gnu --sort=name -cf -  --mtime="$TIMESTAMP" . | $GZIP -n - > $tmp_dir/control.tar.gz )
-rm $tmp_dir/tarX
+	$TAR -X "$tmp_dir/tarX" --format=gnu --sort=name -cpf - --mtime="$TIMESTAMP" . | $GZIP -n - >"$tmp_dir/data.tar.gz"
+	installed_size=$(stat -c "%s" "$tmp_dir/data.tar.gz")
 
-which usign >/dev/null && [ -s "$TOPDIR/key-build" ] && {
-	tmp_concat="$tmp_dir/control+data.tmp"
-	cat "$tmp_dir/data.tar.gz" "$tmp_dir/control.tar.gz" > "$tmp_concat"
-	usign -S -m "$tmp_concat" -s "$TOPDIR/key-build" -x "$tmp_dir/control+data.sig"
-	control_data_sig='./control+data.sig'
+	sed -i -e "s/^Installed-Size: .*/Installed-Size: $installed_size/" \
+		"$pkg_dir/$CONTROL/control"
+
+	(cd "$pkg_dir/$CONTROL" && $TAR --format=gnu --sort=name -cf - --mtime="$TIMESTAMP" . | $GZIP -n - >"$tmp_dir/control.tar.gz")
+	rm "$tmp_dir/tarX"
+
+	[[ -f $sign_file_list ]] || return 0
+
+	cat "$tmp_dir/data.tar.gz" "$tmp_dir/control.tar.gz" >"$tmp_concat"
+	[[ $CI ]] && $CI && tmp_concat=${tmp_concat#"$TOPDIR/"}
+	$prepare && echo "$tmp_concat" >>"$sign_file_list"
+	echo "Prepared $tmp_concat"
 }
 
-echo "2.0" > $tmp_dir/debian-binary
+pack() {
+	local control_data_sig=$1
+	echo "2.0" >"$tmp_dir/debian-binary"
 
-pkg_file=$dest_dir/${pkg}_${version}_${arch}.ipk
-rm -f $pkg_file
-( cd $tmp_dir && $TAR --format=gnu --sort=name -cf -  --mtime="$TIMESTAMP" ./debian-binary ./data.tar.gz ./control.tar.gz $control_data_sig | $GZIP -n - > $pkg_file )
+	pkg_file=$dest_dir/${pkg}_${version}_${arch}.ipk
+	rm -f "$pkg_file"
+	cd "$tmp_dir" && {
+		# shellcheck disable=2086
+		$TAR --format=gnu --sort=name -cf - --mtime="$TIMESTAMP" ./debian-binary ./data.tar.gz ./control.tar.gz $control_data_sig | $GZIP -n - >"$pkg_file"
+		echo "Packaged contents of $pkg_dir into $pkg_file"
+	}
+}
 
-echo "Packaged contents of $pkg_dir into $pkg_file"
+if $prepare; then
+	prepare "$sign_file_list"
+elif $pack; then
+	pack './control+data.sig'
+else
+	prepare
+	pack
+fi
